// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/account/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AccountService service

func NewAccountServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AccountService service

type AccountService interface {
	// RedbagBalanceList 获取用户的红包流水记录
	RedbagBalanceLogList(ctx context.Context, in *RedbagBalanceLogListRequest, opts ...client.CallOption) (*RedbagBalanceLogListResponse, error)
}

type accountService struct {
	c    client.Client
	name string
}

func NewAccountService(name string, c client.Client) AccountService {
	return &accountService{
		c:    c,
		name: name,
	}
}

func (c *accountService) RedbagBalanceLogList(ctx context.Context, in *RedbagBalanceLogListRequest, opts ...client.CallOption) (*RedbagBalanceLogListResponse, error) {
	req := c.c.NewRequest(c.name, "AccountService.RedbagBalanceLogList", in)
	out := new(RedbagBalanceLogListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceHandler interface {
	// RedbagBalanceList 获取用户的红包流水记录
	RedbagBalanceLogList(context.Context, *RedbagBalanceLogListRequest, *RedbagBalanceLogListResponse) error
}

func RegisterAccountServiceHandler(s server.Server, hdlr AccountServiceHandler, opts ...server.HandlerOption) error {
	type accountService interface {
		RedbagBalanceLogList(ctx context.Context, in *RedbagBalanceLogListRequest, out *RedbagBalanceLogListResponse) error
	}
	type AccountService struct {
		accountService
	}
	h := &accountServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AccountService{h}, opts...))
}

type accountServiceHandler struct {
	AccountServiceHandler
}

func (h *accountServiceHandler) RedbagBalanceLogList(ctx context.Context, in *RedbagBalanceLogListRequest, out *RedbagBalanceLogListResponse) error {
	return h.AccountServiceHandler.RedbagBalanceLogList(ctx, in, out)
}
